In [2]:
conda install -c conda-forge gmaps

Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.1
  latest version: 4.10.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Users/gabbyvb/opt/anaconda3

  added / updated specs:
    - gmaps


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.10.3               |   py38h50d1736_2         3.1 MB  conda-forge
    python_abi-3.8             |           2_cp38           4 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.1 MB

The following NEW packages will be INSTALLED:

  geojson            conda-forge/noarch::geojson-2.5.0-py_0
  gmaps              conda-forge/noarch::gmaps-0.9.0-py_0
  python_abi         conda-forge/osx-64::python_abi-3.8-2_cp38

The following packages will be UPDATED:

  conda              pkgs/main::conda-4.10.1-py38hecd8cb5_1 --> conda-forge::conda-4.10.3-py38h50d1736_2



Downloading and Extracting Packages
conda-4.10.3         | 3.1 MB    | ##################################### | 100%
python_abi-3.8       | 4 KB      | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

In [2]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [3]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Qena,EG,2021-10-24 12:03:23,26.1615,32.7183,90.36,10,0,6.73
1,1,Cap Malheureux,MU,2021-10-24 12:01:08,-19.9842,57.6142,78.48,68,38,10.00
2,2,Ribeira Grande,PT,2021-10-24 12:03:23,38.5167,-28.7000,68.40,60,20,11.50
3,3,Srednekolymsk,RU,2021-10-24 12:03:23,67.4500,153.6833,-9.85,96,82,3.31
4,4,Maceio,BR,2021-10-24 12:00:14,-9.6658,-35.7353,89.04,66,75,17.27

In [4]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [5]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [8]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [15]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [16]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [17]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [18]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [19]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [20]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
1,1,Cap Malheureux,MU,2021-10-24 12:01:08,-19.9842,57.6142,78.48,68,38,10.00
4,4,Maceio,BR,2021-10-24 12:00:14,-9.6658,-35.7353,89.04,66,75,17.27
11,11,Pokaran,IN,2021-10-24 12:03:25,26.9167,71.9167,87.06,25,0,2.48
23,23,Cabo San Lucas,MX,2021-10-24 12:03:29,22.8909,-109.9124,75.51,74,5,4.00
24,24,Sur,OM,2021-10-24 12:00:21,22.5667,59.5289,86.00,52,0,6.49
26,26,Kieta,PG,2021-10-24 12:03:29,-6.2167,155.6333,79.57,83,36,4.21
35,35,Butaritari,KI,2021-10-24 12:02:46,3.0707,172.7902,80.46,71,80,1.32
37,37,Dhidhdhoo,MV,2021-10-24 12:00:22,6.8833,73.1000,81.03,79,100,10.04
44,44,Caravelas,BR,2021-10-24 12:03:33,-17.7125,-39.2481,84.00,64,24,7.54
46,46,Itoman,JP,2021-10-24 12:03:34,26.1247,127.6694,75.22,78,75,8.05

In [21]:
preferred_cities_df.count()

City_ID       193
City          193
Country       191
Date          193
Lat           193
Lng           193
Max Temp      193
Humidity      193
Cloudiness    193
Wind Speed    193
dtype: int64

In [22]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

              City Country  Max Temp      Lat       Lng Hotel Name
1   Cap Malheureux      MU     78.48 -19.9842   57.6142
4           Maceio      BR     89.04  -9.6658  -35.7353
11         Pokaran      IN     87.06  26.9167   71.9167
23  Cabo San Lucas      MX     75.51  22.8909 -109.9124
24             Sur      OM     86.00  22.5667   59.5289
26           Kieta      PG     79.57  -6.2167  155.6333
35      Butaritari      KI     80.46   3.0707  172.7902
37       Dhidhdhoo      MV     81.03   6.8833   73.1000
44       Caravelas      BR     84.00 -17.7125  -39.2481
46          Itoman      JP     75.22  26.1247  127.6694

In [23]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [27]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [28]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
1,Cap Malheureux,MU,78.48,-19.9842,57.6142,Pereybere Hotel & Spa
4,Maceio,BR,89.04,-9.6658,-35.7353,Poutur Pousada
11,Pokaran,IN,87.06,26.9167,71.9167,Motel Pokaran - RTDC
23,Cabo San Lucas,MX,75.51,22.8909,-109.9124,Hotel Tesoro Los Cabos
24,Sur,OM,86.00,22.5667,59.5289,Sur Plaza Hotel
26,Kieta,PG,79.57,-6.2167,155.6333,Uruna Bay Retreat
35,Butaritari,KI,80.46,3.0707,172.7902,Isles Sunset Lodge
37,Dhidhdhoo,MV,81.03,6.8833,73.1000,Dhidhoo beach
44,Caravelas,BR,84.00,-17.7125,-39.2481,Pousada dos Navegantes
46,Itoman,JP,75.22,26.1247,127.6694,Southern Beach Hotel & Resort Okinawa

In [29]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [30]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [31]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [32]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))